[build]
  # Base directory is set in the Netlify UI to "telcoinwiki-react".
  # With baseRelDir=true, publish is relative to that base.
  publish = "dist"
  command = "npm run build"
  ignore = "bash tools/netlify-skip-non-main.sh"

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_FLAGS = "--no-audit --no-fund"
  # Align with PR #170 feature flags in production
  VITE_MEGA_MENU_ENABLED = "true"
  VITE_SCROLL_STORY_ENABLED = "true"

[context.branch-deploy]
  # Use the default [build] command and publish paths.

[context.branch-deploy.environment]
  VITE_APP_ENV = "preview"
  VITE_SCROLL_STORY_ENABLED = "true"
  VITE_MEGA_MENU_ENABLED = "true"

[context.deploy-preview]
  # Use the default [build] command and publish paths.

[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"
  VITE_SCROLL_STORY_ENABLED = "true"
  VITE_MEGA_MENU_ENABLED = "true"
