[build]
  publish = "telcoinwiki-react/dist"
  command = "npm ci --no-audit --no-fund && npm --prefix telcoinwiki-react ci --no-audit --no-fund && export VITE_SUPABASE_URL=\"${VITE_SUPABASE_URL:-$NEXT_PUBLIC_SUPABASE_URL}\" && export VITE_SUPABASE_ANON_KEY=\"${VITE_SUPABASE_ANON_KEY:-$NEXT_PUBLIC_SUPABASE_ANON_KEY}\" && npm run prebuild && npm run build && rm -rf node_modules telcoinwiki-react/node_modules"
  ignore = "bash tools/netlify-skip-non-main.sh"

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_FLAGS = "--no-audit --no-fund"
  # Align with PR #170 feature flags in production
  VITE_MEGA_MENU_ENABLED = "true"
  VITE_SCROLL_STORY_ENABLED = "true"

[context.branch-deploy]
  publish = "telcoinwiki-react/dist"
  command = "npm ci --no-audit --no-fund && npm --prefix telcoinwiki-react ci --no-audit --no-fund && export VITE_SUPABASE_URL=\"${VITE_SUPABASE_URL:-$NEXT_PUBLIC_SUPABASE_URL}\" && export VITE_SUPABASE_ANON_KEY=\"${VITE_SUPABASE_ANON_KEY:-$NEXT_PUBLIC_SUPABASE_ANON_KEY}\" && npm run prebuild && npm run build"

[context.branch-deploy.environment]
  VITE_APP_ENV = "preview"
  VITE_SCROLL_STORY_ENABLED = "true"
  VITE_MEGA_MENU_ENABLED = "true"

[context.deploy-preview]
  publish = "telcoinwiki-react/dist"
  command = "npm ci --no-audit --no-fund && npm --prefix telcoinwiki-react ci --no-audit --no-fund && export VITE_SUPABASE_URL=\"${VITE_SUPABASE_URL:-$NEXT_PUBLIC_SUPABASE_URL}\" && export VITE_SUPABASE_ANON_KEY=\"${VITE_SUPABASE_ANON_KEY:-$NEXT_PUBLIC_SUPABASE_ANON_KEY}\" && npm run prebuild && npm run build"

[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"
  VITE_SCROLL_STORY_ENABLED = "true"
  VITE_MEGA_MENU_ENABLED = "true"
