[build]
  publish = "."
  command = "npm install --no-audit --no-fund --include=dev && export VITE_SUPABASE_URL=\"${VITE_SUPABASE_URL:-$NEXT_PUBLIC_SUPABASE_URL}\" && export VITE_SUPABASE_ANON_KEY=\"${VITE_SUPABASE_ANON_KEY:-$NEXT_PUBLIC_SUPABASE_ANON_KEY}\" && npm run build"

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_FLAGS = "--no-audit --no-fund"
