import type { PageMetaMap } from './types'

export const PAGE_META: PageMetaMap = {
  home: { label: 'Home', url: '/index.html', parent: null, navId: null },
  'start-here': {
    label: 'Start Here',
    url: '/start-here.html',
    parent: 'home',
    navId: 'start-here',
    sidebar: true,
  },
  faq: { label: 'FAQ', url: '/faq/', parent: 'home', navId: 'faq', sidebar: true },
  wallet: {
    label: 'Telcoin Wallet',
    url: '/wallet.html',
    parent: 'home',
    navId: 'wallet',
    sidebar: true,
  },
  'digital-cash': {
    label: 'Digital Cash',
    url: '/digital-cash.html',
    parent: 'home',
    navId: 'digital-cash',
    sidebar: true,
  },
  remittances: {
    label: 'Remittances',
    url: '/remittances.html',
    parent: 'home',
    navId: 'remittances',
    sidebar: true,
  },
  'tel-token': {
    label: 'TEL Token',
    url: '/tel-token.html',
    parent: 'home',
    navId: 'tel-token',
    sidebar: true,
  },
  network: {
    label: 'Telcoin Network',
    url: '/network.html',
    parent: 'home',
    navId: 'network',
    sidebar: true,
  },
  telx: {
    label: 'TELx Liquidity',
    url: '/telx.html',
    parent: 'home',
    navId: 'telx',
    sidebar: true,
  },
  governance: {
    label: 'Governance & Association',
    url: '/governance.html',
    parent: 'home',
    navId: 'governance',
    sidebar: true,
  },
  builders: {
    label: 'Builders',
    url: '/builders.html',
    parent: 'home',
    navId: 'builders',
    sidebar: true,
  },
  links: {
    label: 'Official Links',
    url: '/links.html',
    parent: 'home',
    navId: 'links',
    sidebar: true,
  },
  'deep-dive': {
    label: 'Deep Dive',
    url: '/deep-dive.html',
    parent: 'home',
    navId: 'deep-dive',
  },
  pools: {
    label: 'TELx Pools Dashboard',
    url: '/pools.html',
    parent: 'builders',
    navId: 'builders',
  },
  portfolio: {
    label: 'TELx Portfolio Explorer',
    url: '/portfolio.html',
    parent: 'builders',
    navId: 'builders',
  },
  about: {
    label: 'About this project',
    url: '/about.html',
    parent: 'home',
    navId: null,
  },
  '404': {
    label: 'Page not found',
    url: '/404.html',
    parent: 'home',
    navId: null,
  },
}
