import type { PageMetaMap } from './types'

export const PAGE_META: PageMetaMap = {
  home: { label: 'Home', url: '/', parent: null, navId: null },
  problem: {
    label: 'Problem',
    url: '/problem',
    parent: 'home',
    navId: 'problem',
    sidebar: true,
  },
  model: {
    label: 'Model',
    url: '/model',
    parent: 'home',
    navId: 'model',
    sidebar: true,
  },
  engine: {
    label: 'Engine',
    url: '/engine',
    parent: 'home',
    navId: 'engine',
    sidebar: true,
  },
  experience: {
    label: 'Experience',
    url: '/experience',
    parent: 'home',
    navId: 'experience',
    sidebar: true,
  },
  learn: {
    label: 'Learn',
    url: '/learn',
    parent: 'home',
    navId: 'learn',
    sidebar: true,
  },
  faq: { label: 'FAQ', url: '/faq', parent: 'home', navId: 'faq', sidebar: true },
  'deep-dive': {
    label: 'Deep Dive',
    url: '/deep-dive',
    parent: 'learn',
    navId: 'learn',
  },
  builders: {
    label: 'Builders',
    url: '/builders',
    parent: 'learn',
    navId: 'learn',
    sidebar: true,
  },
  links: {
    label: 'Official Links',
    url: '/links',
    parent: 'learn',
    navId: 'learn',
    sidebar: true,
  },
  pools: {
    label: 'TELx Pools Dashboard',
    url: '/pools',
    parent: 'engine',
    navId: 'engine',
  },
  portfolio: {
    label: 'TELx Portfolio Explorer',
    url: '/portfolio',
    parent: 'engine',
    navId: 'engine',
  },
  about: {
    label: 'About this project',
    url: '/about',
    parent: 'learn',
    navId: null,
  },
  '404': {
    label: 'Page not found',
    url: '/404',
    parent: 'home',
    navId: null,
  },
}
