import type { FAQItemData, FAQGroup } from './FAQ'
import { Fragment } from 'react'

export const faqItems: FAQItemData[] = [
  {
    question: 'What is Telcoin?',
    answer: (
      <Fragment>
        <p>Telcoin blends blockchain with the global reach of mobile telecoms to deliver fast, affordable, and compliant financial services to anyone with a phone?especially the underserved.</p>
        <p>By partnering with mobile network operators and financial institutions, Telcoin brings remittances, savings, and payments into existing telecom infrastructure to reach billions of users.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is the Telcoin Association?',
    answer: (
      <Fragment>
        <p>The Telcoin Association is a nonprofit in Switzerland that governs the Telcoin Network. It stewards protocol upgrades, validator onboarding, economic parameters, and overall network governance.</p>
        <p>Through a constitution and council-based model, it keeps development decentralized and aligned with regulatory expectations.</p>
      </Fragment>
    ),
  },
  {
    question: 'What are the Telcoin Association Councils and what does each one do?',
    answer: (
      <Fragment>
        <ul>
          <li><strong>Ecosystem Council</strong>: Grants and funding for projects and partners.</li>
          <li><strong>Technical Council</strong>: Core codebase, upgrades, validator tooling, TIP implementation.</li>
          <li><strong>Staking Council</strong>: Staking parameters, rewards, and penalties.</li>
          <li><strong>Monetary Policy Council</strong>: TEL issuance/inflation parameters.</li>
          <li><strong>Validator Council</strong>: Screens and monitors telecom/institutional validators.</li>
          <li><strong>Treasury Council</strong>: Safeguards and deploys Association resources responsibly.</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: "What?s the difference between Telcoin Holdings and the Telcoin Association?",
    answer: (
      <Fragment>
        <p><strong>Telcoin Holdings</strong> builds consumer products (Wallet, Digital Cash, Bank) and integrations.</p>
        <p><strong>The Telcoin Association</strong> governs the protocol and maintains neutral, community-aligned stewardship of the blockchain.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is the Telcoin token (TEL), and why is it important?',
    answer: (
      <Fragment>
        <p>TEL is the native utility token for gas, staking and rewards, referral incentives, liquidity incentives, and as collateral for Digital Cash issuance?aligning incentives across the ecosystem.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is TANIP-1?',
    answer: (
      <Fragment>
        <p>TANIP-1 is the foundational network incentive framework including referral incentives (Earn TEL), validator incentives, and trading incentives for liquidity providers.</p>
      </Fragment>
    ),
  },
  {
    question: 'How do I earn Telcoin from staking?',
    answer: (
      <Fragment>
        <p>Telcoin uses <strong>Proof of Alignment</strong>. Stake TEL in the app, share your referral code, and earn rewards from activity generated by your referrals. Rewards accrue in real-time and can be claimed anytime.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is the Telcoin Network?',
    answer: (
      <Fragment>
        <ul>
          <li>Ethereum-compatible public L1 designed for telecom distribution</li>
          <li>Narwhal + Bullshark consensus for speed and security</li>
          <li>Permissioned validator set (GSMA-certified operators and regulated institutions)</li>
          <li>Governed by the Telcoin Association</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'What is ?Digital Cash??',
    answer: (
      <Fragment>
        <p>Telcoin?s suite of fiat-backed stablecoins issued by licensed entities with full reserves, enabling remittances, merchant payments, payroll, and savings.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is ?RegFi??',
    answer: (
      <Fragment>
        <p>RegFi is regulated finance?self-custody speed and cost efficiency combined with KYC/AML, consumer protection, and reporting requirements.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is the Telcoin Validator Program?',
    answer: (
      <Fragment>
        <p>GSMA-certified telecom operators and licensed financial institutions can run validators after KYB, staking TEL, and meeting uptime/compliance/technical standards to earn network rewards.</p>
      </Fragment>
    ),
  },
  {
    question: 'What is the Telcoin Improvement Proposal (TIP) process?',
    answer: (
      <Fragment>
        <ul>
          <li><strong>TELIP</strong>: Core protocol upgrades</li>
          <li><strong>TANIP</strong>: Incentive programs</li>
          <li><strong>TGIP</strong>: Governance/Association changes</li>
        </ul>
        <p>Anyone can propose; ideas are discussed publicly and approved through transparent processes.</p>
      </Fragment>
    ),
  },
  {
    question: 'Where can I get involved with the Telcoin community?',
    answer: (
      <Fragment>
        <ul>
          <li><a href="https://www.telco.in" target="_blank" rel="noreferrer">telco.in</a></li>
          <li><a href="https://www.reddit.com/r/telcoin" target="_blank" rel="noreferrer">Reddit</a></li>
          <li><a href="https://twitter.com/telcoin" target="_blank" rel="noreferrer">X (Twitter)</a></li>
          <li><a href="https://t.me/Telcoin_Announcements" target="_blank" rel="noreferrer">Telegram</a></li>
          <li><a href="https://discord.gg/qzMUw57UJa" target="_blank" rel="noreferrer">Discord</a></li>
          <li><a href="https://github.com/Telcoin-Association" target="_blank" rel="noreferrer">GitHub</a></li>
          <li><a href="https://www.youtube.com/@Telcoin_Team" target="_blank" rel="noreferrer">YouTube</a></li>
          <li><a href="https://www.linkedin.com/company/telcoin" target="_blank" rel="noreferrer">LinkedIn</a></li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'Where can I buy Telcoin (TEL)?',
    answer: (
      <Fragment>
        <ul>
          <li><strong>Recommended</strong>: Telcoin Wallet app (iOS & Android)</li>
          <li>DEXs: Uniswap (Ethereum), Balancer (Polygon), QuickSwap</li>
          <li>CEXs: KuCoin, MEXC, Bitrue, Indodax, CoinDCX, CEX.IO</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'What?s Telcoin?s value proposition?',
    answer: (
      <Fragment>
        <p>Telcoin connects mobile networks with blockchain to lower costs, speed cross-border payments, expand access to savings/tools, and align incentives between users, operators, and developers.</p>
      </Fragment>
    ),
  },
  {
    question: 'What are the latest marketing updates?',
    answer: (
      <Fragment>
        <ul>
          <li><strong>SOC 2 Type I Certification</strong> (May 2025)</li>
          <li><strong>Wallet v4 Launch</strong> (Feb 2025)</li>
          <li>Validator onboarding and roadmap releases</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'What is the status of Telcoin Bank and stablecoin initiatives?',
    answer: (
      <Fragment>
        <ul>
          <li>eUSD: first U.S. bank-issued stablecoin under NFIA</li>
          <li>International rollout: eCAD, eZAR, eJPY and more</li>
          <li>Global remittance corridors via telecom rails</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'What?s next for Telcoin?',
    answer: (
      <Fragment>
        <ul>
          <li>Full launch of Telcoin Bank and eUSD</li>
          <li>Expansion of telecom validators</li>
          <li>New stablecoin corridors across regions</li>
          <li>Deeper in-app financial tools (savings, swaps, pay)</li>
          <li>On-chain community governance and Treasury programs</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'Is TEL deflationary?',
    answer: (
      <Fragment>
        <p>Base fees are burned each transaction while an equal amount is regenerated to Treasury each block. Net deflation depends on Treasury policy and issuance vs. spending.</p>
      </Fragment>
    ),
  },
  {
    question: 'What chains support TEL?',
    answer: (
      <Fragment>
        <ul>
          <li><strong>Polygon</strong>: used by the Telcoin Wallet</li>
          <li><strong>Ethereum</strong>: tradable on major DEXs</li>
          <li><strong>Base</strong>: available, not yet supported by the app</li>
        </ul>
        <p>Always verify network compatibility before sending TEL to the app.</p>
      </Fragment>
    ),
  },
  {
    question: 'What are the risks or limitations of using Telcoin today?',
    answer: (
      <Fragment>
        <ul>
          <li>Validator set is small but expanding</li>
          <li>Features may be region-locked or phased</li>
          <li>Alpha-mainnet phase; launches depend on regulation</li>
        </ul>
      </Fragment>
    ),
  },
  {
    question: 'How is Telcoin different from other stablecoin platforms?',
    answer: (
      <Fragment>
        <ul>
          <li>Regulated issuance by a U.S. digital asset bank</li>
          <li>Telco-native distribution</li>
          <li>On-chain governance via TIPs and councils</li>
          <li>Compliance by design (KYC/AML, consumer protection)</li>
        </ul>
      </Fragment>
    ),
  },
]


export const faqGroups: FAQGroup[] = [
  { title: 'About Telcoin', items: [faqItems[0], faqItems[1], faqItems[2], faqItems[3], faqItems[4]] },
  { title: 'Incentives & Staking', items: [faqItems[5], faqItems[6]] },
  { title: 'Network & Technology', items: [faqItems[7], faqItems[10], faqItems[11], faqItems[19]] },
  { title: 'Products & Compliance', items: [faqItems[8], faqItems[9], faqItems[16], faqItems[21]] },
  { title: 'Community & Access', items: [faqItems[12], faqItems[13], faqItems[14], faqItems[15], faqItems[17], faqItems[18], faqItems[20]] },
];

