name: perf
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit --no-fund || npm install
          npm --prefix telcoinwiki-react ci --prefer-offline --no-audit --no-fund || npm --prefix telcoinwiki-react install

      - name: Run performance checks (build + preview + Lighthouse)
        run: npm run perf

      - name: Upload perf artifacts
        uses: actions/upload-artifact@v4
        with:
          name: perf-reports
          path: |
            telcoinwiki-react/tools/perf/
          if-no-files-found: warn

